package com.guojianghao.mapper.sys;

import com.guojianghao.entity.sys.SysResource;
import com.guojianghao.entity.sys.SysResourceExample;
import com.guojianghao.entity.sys.SysRole;

import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysResourceMapper {
    /**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	long countByExample(SysResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int deleteByExample(SysResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int insert(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int insertSelective(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	List<SysResource> selectByExample(SysResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	SysResource selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByExampleSelective(@Param("record") SysResource record, @Param("example") SysResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByExample(@Param("record") SysResource record, @Param("example") SysResourceExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByPrimaryKeySelective(SysResource record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_resource
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByPrimaryKey(SysResource record);

	List<SysResource> getSysChildResourcesListByUserId(int id);
	
	List<SysResource> getSysParentResourcesListByUserId(int id);

	int getsysResourceCount(Map<String, Object> map);

	List<SysRole> getsysResourceList(Map<String, Object> map);

	List<SysResource> getAllResourceList();

	List<SysResource> getSelfResourceList(int roleId);
}