package com.guojianghao.mapper.sys;

import com.guojianghao.entity.sys.SysRole;
import com.guojianghao.entity.sys.SysRoleExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface SysRoleMapper {

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	long countByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int deleteByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int deleteByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int insert(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int insertSelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	List<SysRole> selectByExample(SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	SysRole selectByPrimaryKey(Integer id);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByExampleSelective(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByExample(@Param("record") SysRole record, @Param("example") SysRoleExample example);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByPrimaryKeySelective(SysRole record);

	/**
	 * This method was generated by MyBatis Generator. This method corresponds to the database table sys_role
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	int updateByPrimaryKey(SysRole record);

	List<SysRole> getRoleListByUserId(int id);

	int deleteRoleByUserid(Integer id);

	int saveRole(Integer userId, Integer roleId);

	int getSysRoleCount(Map<String, Object> map);

	List<SysRole> getSysRoleList(Map<String, Object> map);
}