package com.guojianghao.entity.sys;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import com.alibaba.fastjson.JSON;

public class SysResource {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.parent_id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private Integer parentId;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.href
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String href;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.create_time
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private Date createTime;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_resource.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.id
	 * @return  the value of sys_resource.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	
	private List<SysResource> list = new ArrayList<SysResource>();
	
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.id
	 * @param id  the value for sys_resource.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.name
	 * @return  the value of sys_resource.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.name
	 * @param name  the value for sys_resource.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.parent_id
	 * @return  the value of sys_resource.parent_id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public Integer getParentId() {
		return parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.parent_id
	 * @param parentId  the value for sys_resource.parent_id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setParentId(Integer parentId) {
		this.parentId = parentId;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.href
	 * @return  the value of sys_resource.href
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getHref() {
		return href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.href
	 * @param href  the value for sys_resource.href
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setHref(String href) {
		this.href = href;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.create_time
	 * @return  the value of sys_resource.create_time
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public Date getCreateTime() {
		return createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.create_time
	 * @param createTime  the value for sys_resource.create_time
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.status
	 * @return  the value of sys_resource.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.status
	 * @param status  the value for sys_resource.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_resource.description
	 * @return  the value of sys_resource.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_resource.description
	 * @param description  the value for sys_resource.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	public List<SysResource> getList() {
		return list;
	}

	public void setList(List<SysResource> list) {
		this.list = list;
	}

	@Override
    public String toString() {
    	return JSON.toJSONString(this);
    }
}