package com.guojianghao.entity.sys;

import com.alibaba.fastjson.JSON;

public class SysRole {
    /**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private Integer id;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String name;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String status;
	/**
	 * This field was generated by MyBatis Generator. This field corresponds to the database column sys_role.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	private String description;

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.id
	 * @return  the value of sys_role.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public Integer getId() {
		return id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.id
	 * @param id  the value for sys_role.id
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setId(Integer id) {
		this.id = id;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.name
	 * @return  the value of sys_role.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getName() {
		return name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.name
	 * @param name  the value for sys_role.name
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setName(String name) {
		this.name = name;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.status
	 * @return  the value of sys_role.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getStatus() {
		return status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.status
	 * @param status  the value for sys_role.status
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setStatus(String status) {
		this.status = status;
	}

	/**
	 * This method was generated by MyBatis Generator. This method returns the value of the database column sys_role.description
	 * @return  the value of sys_role.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public String getDescription() {
		return description;
	}

	/**
	 * This method was generated by MyBatis Generator. This method sets the value of the database column sys_role.description
	 * @param description  the value for sys_role.description
	 * @mbg.generated  Thu Sep 21 14:21:59 SGT 2017
	 */
	public void setDescription(String description) {
		this.description = description;
	}

	@Override
    public String toString() {
    	return JSON.toJSONString(this);
    }
}